@host = http://localhost:8080

###
POST {{host}}/task
Content-Type: application/json

{
    "task": {
        "title": "task title",
        "description": "description task"
    }
}

###
GET {{host}}/task

###
GET {{host}}/task/a5907310-357c-494c-94e8-f22b220fd528

###
PUT {{host}}/task/a5907310-357c-494c-94e8-f22b220fd528
Content-Type: application/json

{
    "task": {
        "title": "task title updated",
        "description": "description task updated"
    }
}

###
DELETE {{host}}/task/a5907310-357c-494c-94e8-f22b220fd528