PUT http://localhost:8080/add
Content-Type: application/json

{
    "method": "GET",
    "url": "https://google.ru"
}

###
GET http://localhost:8080/get

###
DELETE http://localhost:8080/delete
Content-Type: application/json

{
    "id": 1
}

###
GET http://localhost:8080/responses