PUT http://localhost:8080/add
Content-Type: application/json

{
    "method": "GET",
    "url": "https://google.ru"
}

###
GET http://localhost:8080/get

###
DELETE http://localhost:8080/delete
Content-Type: application/json

{
    "id": "46c7f688-1f8e-4be6-b294-51162283734d"
}

###
GET http://localhost:8080/responses